/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/rosalia2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useFrame } from '@react-three/fiber'

export const Rosalia = (props) => {
  const { nodes, materials } = useGLTF('./Models/rosalia2.glb')
  const ref = useRef();
  const tl = useRef();

  //use gsap to animate the position of the model
  useFrame(() => {
    if (tl.current) {
      tl.current.progress();
    }
  });

  //use gsap to animate the position of the model one time
  React.useEffect(() => {
    tl.current = gsap.timeline({ repeat: 0, yoyo: false });
    tl.current.to(ref.current.position, {
      duration: 3,
      x: 0,
      y: 0,
      z: 0,
      ease: "power1.inOut",
    });
  }, []);
  return (
<group {...props} dispose={null} ref={ref} position={[0, -250, 0]}>      
<mesh
        castShadow
        receiveShadow
        geometry={nodes.Fonsterkarm_MeshPart1.geometry}
        material={materials.Material__295}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fonsterkarm_MeshPart2.geometry}
        material={materials.Material__296}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fonsterkarm_MeshPart0.geometry}
        material={materials.Material__293}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fasad.geometry}
        material={materials.Material__292}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fasad_2.geometry}
        material={materials.Material__290}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Omgivning.geometry}
        material={materials.Material__294}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cykelstall.geometry}
        material={materials.Material__280}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <group
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Balkongracken_1.geometry}
          material={materials.fence001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Balkongracken_2.geometry}
          material={materials.Racke}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tak.geometry}
        material={materials.Material__301}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vaggar_2.geometry}
        material={materials.innerwalls001}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vaggar_1.geometry}
        material={materials.Vit_1}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Takdetaljer.geometry}
        material={materials.Material__302}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stuprannor.geometry}
        material={materials.Material__300}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Innevaggar.geometry}
        material={materials.innerwalls001}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Innetak.geometry}
        material={materials.Innetak1}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Golv.geometry}
        material={materials.Ek_trestav}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fonster_glas.geometry}
        material={materials.Fonster_Glas}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Botten.geometry}
        material={materials.Material__291}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Balkonger.geometry}
        material={materials.Material__287}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Armatur.geometry}
        material={materials.lambert54}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Innegard_mark.geometry}
        material={materials.Material__298}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Exterior_mark.geometry}
        material={materials.Material__282}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bankar.geometry}
        material={materials.Material__289}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AM113_062_Tilia24.geometry}
        material={materials.Material__286}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AM113_062_Tilia23.geometry}
        material={materials.Material__285}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AM113_062_Tilia3.geometry}
        material={materials.Material__284}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AM113_062_Tilia2.geometry}
        material={materials.Material__283}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AM113_009_Ulmus.geometry}
        material={materials.Material__281}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.garagedor.geometry}
        material={materials.Material__297}
        position={[31.831, -6.447, 14.447]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box003.geometry}
        material={materials.Balkong}
        position={[29.255, -7.455, 32.582]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plank.geometry}
        material={materials["Material #306"]}
        position={[22.348, -7.585, 9.682]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Innegard_mark001.geometry}
        material={materials.Material__298}
        position={[22.459, -7.6, 9.391]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.038}
      />      </group>     
    )
}

useGLTF.preload('./Models/rosalia2.glb')
